In [1]:
# SVM Classification
import pandas as pd
import numpy as np
from pandas import read_csv
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import StandardScaler

from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report


from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score


In [2]:
animal = read_csv("zoo.csv")
animal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   animal name  101 non-null    object
 1   hair         101 non-null    int64 
 2   feathers     101 non-null    int64 
 3   eggs         101 non-null    int64 
 4   milk         101 non-null    int64 
 5   airborne     101 non-null    int64 
 6   aquatic      101 non-null    int64 
 7   predator     101 non-null    int64 
 8   toothed      101 non-null    int64 
 9   backbone     101 non-null    int64 
 10  breathes     101 non-null    int64 
 11  venomous     101 non-null    int64 
 12  fins         101 non-null    int64 
 13  legs         101 non-null    int64 
 14  tail         101 non-null    int64 
 15  domestic     101 non-null    int64 
 16  catsize      101 non-null    int64 
 17  type         101 non-null    int64 
dtypes: int64(17), object(1)
memory usage: 14.3+ KB


In [3]:
animal= animal.rename(columns={"animal name":"animal_name"})

In [4]:
#check if there are duplicates in animal_name
duplicates = animal.animal_name.value_counts()
duplicates[duplicates > 1]

frog    2
Name: animal_name, dtype: int64

In [5]:
#select these duplicates frog
frog = animal.loc[animal['animal_name'] == 'frog']
frog

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
25        frog     0         0     1     0         0        1         1   
26        frog     0         0     1     0         0        1         1   

    toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
25        1         1         1         0     0     4     0         0   
26        1         1         1         1     0     4     0         0   

    catsize  type  
25        0     5  
26        0     5

In [6]:
# observation: find that one frog is venomous and another one is not 
#              change the venomous one into frog2 to seperate 2 kinds of frog 
animal['animal_name'][(animal.venomous == 1 )& (animal.animal_name == 'frog')] = "frog2"

C:\Users\saiki\AppData\Local\Temp/ipykernel_8588/3296219602.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  animal['animal_name'][(animal.venomous == 1 )& (animal.animal_name == 'frog')] = "frog2"


In [7]:
# finding Unique value of hair
color_list = [("red" if i == 1 else "blue" if i == 0 else "yellow" ) for i in animal.hair]
unique_color = list(set(color_list))
unique_color

['red', 'blue']

In [15]:
# split train test data into 70/30.
from sklearn.model_selection import train_test_split
x = animal.iloc[:,1:17]
y = animal.iloc[:,17]

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3)

In [17]:
print("X_train shape : ",X_train.shape)
print("X_test shape : ",X_test.shape)
print("y_train shape : ",y_train.shape)
print("y_test shape : ",y_test.shape)

X_train shape :  (70, 16)
X_test shape :  (31, 16)
y_train shape :  (70,)
y_test shape :  (31,)


In [18]:
from sklearn.svm import SVC
svm = SVC(random_state = 42,kernel = "linear")
svm.fit(x_train,y_train)
y_pred_svm = svm.predict(x_test)
print("Train Accurary : ",svm.score(x_train,y_train))
print("Test Accuray : ",svm.score(x_test,y_test))

Train Accurary :  1.0
Test Accuray :  0.967741935483871


In [19]:
from sklearn.metrics import confusion_matrix,classification_report
cm_svm = confusion_matrix(y_test,y_pred_svm)
cr_svm = classification_report(y_test,y_pred_svm)
print("confusion matrix : \n",cm_svm)
print("classification report : \n",cr_svm)

confusion matrix : 
 [[11  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0]
 [ 0  0  1  0  0  0  0]
 [ 0  0  0  3  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0  4  0]
 [ 0  0  0  0  0  1  2]]
classification report : 
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00         8
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         3
           5       1.00      1.00      1.00         1
           6       0.80      1.00      0.89         4
           7       1.00      0.67      0.80         3

    accuracy                           0.97        31
   macro avg       0.97      0.95      0.96        31
weighted avg       0.97      0.97      0.97        31

